version: '3'

services:
  omot:
    image: ghcr.io/ayanamists/oh-my-old-tweet:release
    volumes:
      - "${MEDIA_STORAGE}:/opt/media"

  omot-db:
    image: mysql
    command: --binlog-format=ROW
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: omot_db

  redis:
    image: 'redis:latest'
  
  search:
    image: 'getmeili/meilisearch:v1.5'
    volumes:
      - ./search-data:/meili_data
    command: meilisearch --master-key="MASTER_KEY"

  meilisync:
    image: long2ice/meilisync:dev
    volumes:
      - ./meilisync/config.yml:/meilisync/config.yml
    restart: always
    command: /bin/bash -c "sleep 10 && exec meilisync start"
    depends_on:
      - redis
      - search
      - omot-db

  gateway:
    image: nginx
    ports:
      - "3142:3142"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${MEDIA_STORAGE}:/var/www/media