-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "lastModified" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastModified" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
